[package]
name = 'bloguer'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
bloguer_address = 'a4d97c4aa94db117eaaca6d16b1b5a7be536d75a8747a964086ef44fc9b30392'
